# Generated by Django 3.2.6 on 2021-09-01 17:31

import digestai.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('digestai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyset',
            name='flashcards',
            field=djongo.models.fields.ArrayField(default=None, model_container=digestai.models.FlashCard),
        ),
        migrations.AddField(
            model_name='studyset',
            name='quiz',
            field=djongo.models.fields.ArrayField(default=None, model_container=digestai.models.MultipleChoiceQuestion),
        ),
    ]
